# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

psi <- function(x, y) {
    .Call(`_classCleaner_psi`, x, y)
}

#' @title tmp function
#' @export
sim_by_class <- function(n, Nk, s, tau, rho) {
    .Call(`_classCleaner_sim_by_class`, n, Nk, s, tau, rho)
}

sim_by_instance <- function(n, Nk, s, rho) {
    .Call(`_classCleaner_sim_by_instance`, n, Nk, s, rho)
}

